# Generated by Django 4.2.4 on 2024-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
            ],
            options={
                "db_table": "t_student",
            },
        ),
    ]
