# Generated by Django 4.2.4 on 2024-03-02 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userinfo",
            table="t_student",
        ),
    ]
