# Generated by Django 4.2.4 on 2023-08-22 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="pwd",
            new_name="password",
        ),
    ]
