# Generated by Django 4.2.4 on 2023-08-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_rename_pwd_userinfo_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16)),
            ],
        ),
    ]
